name: container build

on:
  push:
    branches: ['main']

jobs:
  run-command:
    runs-on: censys-org
    container:
      image: gcr.io/censys-internal/censys.io/packer
      options: --user root
      env:
        PACKER_PLUGIN_PATH: "."
      volumes:
          - /tmp:/tmp
          - /runner/_work:/runner/_work
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Credentials Variable
        shell: bash
        run: packer init . && packer build .